routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'dashboard'], function() {
    Auth::routes([
        'register' => false,
        'reset' => false,
        'verify' => false,
    ]);
});

Route::get('/', 'Virtual360Controller@index');

Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard'], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');

    Route::resource('categories', 'CategoriesController');

    Route::resource('books', 'BooksController');
    
    /**
     * Profile & User Route
     */
    Route::get('profile', 'UsersController@profile')->name('profile');
    Route::patch('profile/{user}', 'UsersController@profileUpdate')->name('profile.update');
    Route::resource('users', 'UsersController');

    /**
     * Roles & Permissions Administrator Route
     */
    Route::resource('roles', 'RolesController');
    Route::patch('permissions/sort-module', 'PermissionsController@sortModule')->name('permissions.sort-module');
    Route::resource('permissions', 'PermissionsController', ['except' => [
        'create', 'show', 'edit'
    ]]);
});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $table = 'Books';
    protected $fillable = [
        'category_id',
        'title',
        'image',
        'stock',
        'price'
    ];

    public function category()
    {
        return $this->belongsTo('App\Category', 'category_id', 'id');
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class BooksController extends Controller
{

    private $pathFolder = 'uploads/book_images/';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with(['category'])->orderBy('created_at', 'DESC')->get();

        return view('backend.books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('name', 'ASC')->get();

        return view('backend.books.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'         => 'string|required',
            'image'         => 'required|mimes:png,jpg,jpeg|max:1048',
            'category_id'   => 'required',
            'price'         => 'required',
            'stock'         => 'required'
        ],
        
        [
            'required'  => ':attribute harus diisi',
            'mimes'     => 'Gambar tidak sesuai format',
            'max'       => 'Maksimal ukuran gambar adalah 1Mb'
        ],
        [
            'title'         => 'Judul Buku',
            'image'         => 'Gambar Buku',
            'category_id'   => 'Kategori Buku',
            'price'         => 'Harga Buku',
            'stock'         => 'Stok Buku'
        ]);

        $image                = $request->file('image');
        $image_name           = $request->get('title') . '-buku-' . Str::random(4) . '-' . time() . '.' . $image->getClientOriginalExtension();
        $request->image->move(public_path($this->pathFolder), $image_name);

        Book::create([
            'category_id'       => $request->get('category_id'),
            'title'             => $request->get('title'),
            'image'             => $image_name,
            'stock'             => $request->get('stock'),
            'price'             => str_replace(',', '', $request->get('price')),
        ]);

        return redirect()->route('books.index')->with('success', 'Buku berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $categories = Category::orderBy('name', 'ASC')->get();
        $book = Book::find($id);

        return view('backend.books.edit', compact('categories', 'book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'         => 'string|required',
            'image'         => 'mimes:png,jpg,jpeg|max:1048',
            'category_id'   => 'required',
            'price'         => 'required',
            'stock'         => 'required'
        ],
        
        [
            'required'  => ':attribute harus diisi',
            'mimes'     => 'Gambar tidak sesuai format',
            'max'       => 'Maksimal ukuran gambar adalah 1Mb'
        ],
        [
            'title'         => 'Judul Buku',
            'image'         => 'Gambar Buku',
            'category_id'   => 'Kategori Buku',
            'price'         => 'Harga Buku',
            'stock'         => 'Stok Buku'
        ]);

        $book = Book::find($id);

        if ($request->hasFile('image')) {
            $image                = $request->file('image');
            $image_name           = $request->get('title') . '-buku-' . Str::random(4) . '-' . time() . '.' . $image->getClientOriginalExtension();
            $request->image->move(public_path($this->pathFolder), $image_name);

            if (File::exists($this->pathFolder . $book->image)) {
                File::delete($this->pathFolder . $book->image);
            }
        } else {
            $image_name = $book->image;
        }

        $book->update([
            'category_id'       => $request->get('category_id'),
            'title'             => $request->get('title'),
            'image'             => $image_name,
            'stock'             => $request->get('stock'),
            'price'             => str_replace(',', '', $request->get('price')),
        ]);

        return redirect()->route('books.index')->with('success', 'Buku berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $book = Book::find($id);

        if (File::exists($this->pathFolder . $book->image)) {
            File::delete($this->pathFolder . $book->image);
        }

        $book->delete();

        return response()->json(['status' => true, 'message' => 'Buku Berhasil dihapus']);
    }
}

resources/views/backend/books/create.blade.php
@extends('layouts.backend.app')

@section('title', 'Dashboard')

@section('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.css">
<link rel="stylesheet" href="{{ asset('modules/datatables/datatables.css') }}">
<link rel="stylesheet" href="{{ asset('modules/select2/css/select2.min.css') }}">
@endsection

@section('content')
<div class="section-header border-top">

    <div class="section-header-back">
        <a href="{{ route('books.index') }}" class="btn btn-icon">
            <i class="fas fa-arrow-left"></i>
        </a>
    </div>

    <h1>Tambah Kategori Buku</h1>

</div>

<div class="row">
    <div class="col-sm-6">

        <div class="card">

            <form method="POST" action="{{ route('books.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Ups!</strong> ada masalah pada saat membuat acara.
                            <br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>
                                        {{ $error }}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="form-group">
                        <label for="bgImage">Gambar Buku</label>
                        <input type="file" name="image" class="dropify" data-max-file-size="1M" data-allowed-file-extensions="jpg jpeg png" data-max-file-size-preview="1M" />
                        <small class="text-muted">Maksimal gambar yang bisa diupload : 1MB</small>
                    </div>
    
                    <div class="form-group">
                        <label for="name">Judul Buku</label>
                        <input type="text" name="title" id="title" class="form-control" value="{{ old('title') }}" placeholder="Contoh Buku upin upin..." required autofocus>
                    </div>

                    <div class="form-group">
                        <label for="category_id">Kategori Buku</label>
                        <select class="form-control select2" name="category_id" id="category_id" data-placeholder="Pilih Kategori Buku">
                            <option></option>
                            @foreach ($categories as $item)
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>

                    </div>

                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="name">Harga Buku</label>
                                <input type="text" name="price" id="price" class="form-control" value="{{ old('price') }}" required autofocus>
                                <small class="text-muted">Contoh: 200,000</small>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="name">Stok Buku</label>
                                <input type="number" name="stock" id="stock" class="form-control" value="{{ old('name') }}" required autofocus>
                                <small class="text-muted">Masukkan angka saja</small>
                            </div>
                        </div>
                    </div>
    
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>    
            </form>

        </div>

    </div>
</div>
@endsection

@section('javascript')
<script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"></script>
<script src="{{ asset('modules/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('modules/sweetalert/sweetalert.min.js') }}"></script>
<script src="{{ asset('modules/select2/js/select2.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/cleave.js@1.6.0/dist/cleave.min.js"></script>
<script>

    $('#dataTable').DataTable()
    $('.dropify').dropify();

    var cleave = new Cleave('#price', {
        numeral: true,
        numeralThousandsGroupStyle: 'thousand'
    });

</script>
@endsection

resources/views/backend/books/edit.blade.php
@extends('layouts.backend.app')

@section('title', 'Dashboard')

@section('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.css">
<link rel="stylesheet" href="{{ asset('modules/datatables/datatables.css') }}">
<link rel="stylesheet" href="{{ asset('modules/select2/css/select2.min.css') }}">
@endsection

@section('content')
<div class="section-header border-top">

    <div class="section-header-back">
        <a href="{{ route('books.index') }}" class="btn btn-icon">
            <i class="fas fa-arrow-left"></i>
        </a>
    </div>

    <h1>Edit Kategori Buku</h1>

</div>

<div class="row">
    <div class="col-sm-6">

        <div class="card">

            <form method="POST" action="{{ route('books.update', $book->id) }}" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="card-body">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Ups!</strong> ada masalah pada saat membuat acara.
                            <br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>
                                        {{ $error }}
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="form-group">
                        <label for="bgImage">Gambar Buku</label>
                        <input type="file" name="image" class="dropify" data-max-file-size="1M" data-allowed-file-extensions="jpg jpeg png" data-max-file-size-preview="1M" data-default-file="{{ asset('uploads/book_images/' . $book->image) }}" />
                        <small class="text-muted">Maksimal gambar yang bisa diupload : 1MB</small>
                    </div>
    
                    <div class="form-group">
                        <label for="name">Judul Buku</label>
                        <input type="text" name="title" id="title" class="form-control" value="{{ $book->title }}" placeholder="Contoh Buku upin upin..." required autofocus>
                    </div>

                    <div class="form-group">
                        <label for="category_id">Kategori Buku</label>
                        <select class="form-control select2" name="category_id" id="category_id" data-placeholder="Pilih Kategori Buku">
                            <option></option>
                            @foreach ($categories as $item)
                            <option value="{{ $item->id }}" {{ $item->id === $book->category->id ? 'selected' : '' }}>{{ $item->name }}</option>
                            @endforeach
                        </select>

                    </div>

                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="name">Harga Buku</label>
                                <input type="text" name="price" id="price" class="form-control" value="{{ $book->price }}" required autofocus>
                                <small class="text-muted">Contoh: 200,000</small>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="name">Stok Buku</label>
                                <input type="number" name="stock" id="stock" class="form-control" value="{{ $book->stock }}" required autofocus>
                                <small class="text-muted">Masukkan angka saja</small>
                            </div>
                        </div>
                    </div>
    
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>    
            </form>

        </div>

    </div>
</div>
@endsection

@section('javascript')
<script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"></script>
<script src="{{ asset('modules/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('modules/sweetalert/sweetalert.min.js') }}"></script>
<script src="{{ asset('modules/select2/js/select2.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/cleave.js@1.6.0/dist/cleave.min.js"></script>
<script>

    $('#dataTable').DataTable()
    $('.dropify').dropify();

    var cleave = new Cleave('#price', {
        numeral: true,
        numeralThousandsGroupStyle: 'thousand'
    });

</script>
@endsection

resources/views/backend/books/index.blade.php
@extends('layouts.backend.app')

@section('title', 'Dashboard')

@section('styles')
<link rel="stylesheet" href="{{ asset('modules/datatables/datatables.css') }}">
@endsection

@section('content')
<div class="section-header border-top">
    <h1>Buku</h1>

    <div class="section-header-button ml-auto">
        <a href="{{ route('books.create') }}" class="btn btn-primary">
            Tambah Buku
        </a>
    </div>

</div>

<div class="row">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-body">
                <table class="table table-striped data-table" id="dataTable">
                    <thead>
                        <tr>
                            <th width="5%">#</th>
                            <th width="30%">Gambar Buku</th>
                            <th>Judul Buku</th>
                            <th>Kategori Buku</th>
                            <th>Stok Buku</th>
                            <th>Harga Buku</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($books as $item)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    <img src="{{ asset('uploads/book_images/' . $item->image) }}" alt="{{ $item->image }}" width="80" height="80">
                                </td>
                                <td>{{ $item->title }}</td>
                                <td>
                                    {{ $item->category->name }}
                                </td>
                                <td>{{ $item->stock }}</td>
                                <td>{{ $item->price }}</td>
                                <td>
                                    <div class="btn-group mr-2">
                                        <button type="submit" id="button-delete-{{ $item->id }}" class="btn btn-action btn-danger" data-route="{{ route('books.destroy', $item->id) }}" onclick="delete_data({{ $item->id }})">Hapus</button>
                                    </div>
                                    <div class="btn-group">
                                        <a class="btn btn-action btn-info" href="{{ route('books.edit', $item->id) }}">Edit</a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        
                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>
@endsection

@section('javascript')
<script src="{{ asset('modules/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('modules/sweetalert/sweetalert.min.js') }}"></script>
<script>

    var tableData = $('#dataTable').DataTable()

    @if($message = Session::get('success'))
        toastr.success('{{ $message }}', 'Success')
    @endif

    function delete_data(id)
        {
            var formUrl = $('#button-delete-' + id).data('route');

            swal({
                title: 'Yakin?',
                text: 'Apakah kamu ingin menghapus data ini?',
                buttons: {
                    cancel: true,
                    confirm: {
                        text: 'Hapus!',
                        closeModal: false
                    }
                },
                dangerMode: true,
                closeOnClickOutside: false
            })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        headers: {'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')},
                        type: 'DELETE',
                        url: formUrl,
                        dataType: 'JSON',
                        data: {'id': id, '_token': '{{ csrf_token() }}'},
                        success: function(res)
                        {
                            swal.stopLoading()
                            swal.close()

                            if (res.status === true) {
                                toastr.success(res.message, 'Success')
                                location.reload()
                            }
                        },
                        error: function(jqXHR, textStatus, errorthrown)
                        {
                            console.log(jqXHR);
                            swal.stopLoading()
                            swal.close()
                            toastr.error('Gagal menghapus Data', 'Error')
                        }
                    })
                }
            })
        }



</script>
@endsection